name: 'Sphinx Build'
description: 'Builds documentation using Sphinx.' 
author: 'Brent Maranzano'
branding:
  icon: 'book'
  color: 'yellow'
inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  build-command:
    description:
      The command used to build your documentation. Example
      "sphinx-build -b html . /_build/html"
    required: true
    default: make html
  pre-build-command:
    description:
      Run before the build command. Example
      "apt-get update -y && apt-get install -y perl && pip install sphinx-rtd-theme"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
